# Generated by Django 5.2.7 on 2025-10-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventanalytics",
            old_name="last_updated",
            new_name="last_update",
        ),
    ]
